#!/usr/bin/env python3
"""Reads two CMS Medicare Advantage CSV files and generates one well-known payer JSON file per unique payer name.

Previous approach: one file per contract_id, FPI derived from contract_id.
                   (That was a mistake in reasoning: contract IDs identify
                   contracts, not payer legal entities, and must never be used
                   as an FPI source by this seed.)
Current approach:  one file per unique *normalized payer name*, FPI derived
                   from the LEGAL_NAME_HASH identifier system.

Endpoint coverage
-----------------
The plan census in PlanCrosswalk2026_10012025.csv is the primary source: every
payer that has plans in the crosswalk gets a seed file, whether or not an
endpoint URL is known for it.  payer_url_list.csv contributes two things and
only two things: the payer legal name attached to each contract ID, and (when
present and usable) a provider directory endpoint URL.

Two response formats in that file yield usable endpoints, each recorded under
its own key in plan_endpoints:

* "FHIR JSON" -> davinci_pdex_provider_directory_endpoint#1.1
* "Machine-readable JSON" -> cms_provider_directory_machine_readable_format_endpoint
  (the non-FHIR CMS provider directory index file; see
  reference_data/endpoint_types.json)

A contract whose URL cell is empty, or that lists several space-separated URLs
(no multi-URL strategy is defined yet), still produces a seed file.  Its
plan_group simply carries an empty "plan_endpoints" object, which per
WellKnownFileFormat.md means the index makes no assertion about that payer's
endpoints yet.  These "empty" seed files exist so that the FPI, the contract
IDs, and the plan roster are published and curatable now, with endpoints filled
in later.

A contract that appears in the crosswalk but never in payer_url_list.csv has no
legal name anywhere in the source data.  Since the FPI is a hash of the legal
name, and contract IDs must never be used as an FPI source, such contracts
cannot be seeded; they are counted and reported at the end of the run.

The legal name is the only payer attribute reliably available to CMS at seed
time, so the seed hashes it — a temporary hack until payers publish FPIs
derived from real identifier systems (NAIC_ID, HIOS_ID, LEI, etc.).

All uuid generation and legal-name normalization logic lives in
tools/FPI_maker_cli.py (the single home of FPI hashing in this repository).
The normalization rule applied there: lowercase the raw payer name, then strip
every character that is not a-z or 0-9 (e.g. "AETNA HEALTH, INC." becomes
"aetnahealthinc").  Multiple contract IDs that produce the same normalized
name are treated as the same payer entity and are consolidated into a single
well-known JSON file.  Plans from different contracts that point to different
FHIR endpoints are placed in separate plan_groups within that one file.
"""

import csv
import json
import os
import re
import sys
import uuid

# Locate the source data and output directories relative to this script's location.
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))

PAYER_URL_FILE = os.path.join(SCRIPT_DIR, "source_data", "payer_url_list.csv")
PLAN_CROSSWALK_FILE = os.path.join(SCRIPT_DIR, "source_data", "PlanCrosswalk2026_10012025.csv")
OUTPUT_BASE_DIR = os.path.join(REPO_ROOT, "payer_index_files", "medicare_advantage")

# Import the shared FPI generation library from the tools directory.
TOOLS_DIR = os.path.join(REPO_ROOT, "tools")
if TOOLS_DIR not in sys.path:
    sys.path.insert(0, TOOLS_DIR)
from FPI_maker_cli import generate_fpi, normalize_legal_name  # noqa: E402

# System URI strings used in the identifier and plan_identifiers blocks.
# These correspond to entries in reference_data/current_payer_identification_systems.json.
# FPI: the Federated Payer Identifier generated by this project.
SYSTEM_FPI = "https://directory.cms.gov/payer_identification_system/fpi"
# CMS_CONTRACT_ID: the Medicare Advantage contract ID that most of the source data is coded in.
SYSTEM_CMS_CONTRACT_ID = "https://directory.cms.gov/payer_identification_system/cms_contract_id"
# LEGAL_NAME_HASH: the identifier system used by this seed to generate the FPI
# (a UUID5 derived from the normalized payer legal name).  Recorded on the FPI
# identifier entry as "fpi_source_system".
SYSTEM_LEGAL_NAME_HASH = "https://directory.cms.gov/payer_identification_system/legal_name_hash"
# Medicare plan identifier: the CMS contract ID plus plan segment (e.g. "H3146-001").
SYSTEM_MEDICARE_PLAN = "https://directory.cms.gov/payer_identification_system/cms_contract_id/plan/plan_id"
RESOURCE_TYPE = "http://hl7.org/fhir/us/fast-ndh/StructureDefinition/NDHPayerWellknownDefinition"

# Endpoint keys extractable from this data source, selected per row by the
# "Response Format" column of payer_url_list.csv.
#
# FHIR JSON rows point at a Da Vinci PDex Plan-Net provider directory server.
ENDPOINT_KEY = "davinci_pdex_provider_directory_endpoint#1.1"
# Machine-readable JSON rows point at the non-FHIR CMS provider directory index
# file (the format first used for healthcare.gov, later adopted for Medicare
# Advantage).  See reference_data/endpoint_types.json.  It carries no IG version,
# so like "payer_homepage" the key has no "#version" suffix.
MACHINE_READABLE_ENDPOINT_KEY = "cms_provider_directory_machine_readable_format_endpoint"

# System ID used as the FPI namespace when deriving identifiers from payer names.
# LEGAL_NAME_HASH is the hashing system defined in
# reference_data/current_payer_identification_systems.json; FPI_maker_cli
# normalizes the legal name automatically before hashing under this system.
FPI_SYSTEM_ID = "LEGAL_NAME_HASH"


def safe_name(name):
    """Convert a payer name to a lowercase, underscore-separated, special-character-free directory name."""
    name = name.lower().replace(" ", "_")
    name = re.sub(r"[^a-z0-9_]", "", name)
    name = re.sub(r"_+", "_", name).strip("_")
    return name


def parse_contract_id_field(field_value):
    """Split the combined 'H0028 - PAYER NAME' field into separate contract_id and payer_name strings."""
    parts = field_value.split(" - ", 1)
    if len(parts) == 2:
        return parts[0].strip(), parts[1].strip()
    return None, None


def load_payer_urls(filepath):
    """Read the payer URL CSV and return a dict of contract_id -> {payer_name, url}.

    Every row that yields a contract ID and a payer name is kept, because the
    payer name is what the FPI is hashed from and is therefore the one piece of
    data this seed cannot proceed without.  The URL is optional: rows whose URL
    is unusable (empty, machine-readable JSON, or several URLs in one cell) are
    kept with url set to "" so the payer still gets a seed file, just one that
    asserts no endpoint.
    """
    payers = {}
    stats = {
        "total": 0,
        "no_url": 0,
        "machine_readable": 0,
        "multi_url": 0,
        "skipped_no_contract_id": 0,
        "with_url": 0,
        "processed": 0,
    }

    with open(filepath, encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            stats["total"] += 1

            response_format = row.get("Response Format", "").strip()
            url = row.get("URL", "").strip()
            contract_id_field = row.get("Contract ID", "").strip()

            # Without a contract ID the row cannot be joined to the crosswalk,
            # and without a payer name there is nothing to hash into an FPI.
            contract_id, payer_name = parse_contract_id_field(contract_id_field)
            if not contract_id or not payer_name:
                stats["skipped_no_contract_id"] += 1
                continue

            # Decide whether the URL cell is usable, and which endpoint key it
            # belongs under.  An unusable URL is not a reason to drop the payer —
            # it only means this seed asserts no endpoint for it.
            endpoint_key = ENDPOINT_KEY
            if not url:
                stats["no_url"] += 1
                url = ""
            elif " " in url:
                # Multiple space-separated URLs; no multi-URL strategy defined yet.
                stats["multi_url"] += 1
                url = ""
            elif response_format.lower() == "machine-readable json":
                # Not a FHIR endpoint: this is the CMS machine-readable provider
                # directory index file, published under its own endpoint key.
                stats["machine_readable"] += 1
                endpoint_key = MACHINE_READABLE_ENDPOINT_KEY
            else:
                stats["with_url"] += 1

            payers[contract_id] = {
                "payer_name": payer_name,
                "url": url,
                "endpoint_key": endpoint_key,
            }
            stats["processed"] += 1

    return payers, stats


def load_plan_crosswalk(filepath):
    """Read the plan crosswalk CSV and return a dict of contract_id -> list of unique {plan_id, plan_name} entries."""
    crosswalk = {}
    seen = set()  # Tracks (contract_id, plan_id, plan_name) tuples to prevent duplicate plan entries.

    with open(filepath, encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            contract_id = row.get("CURRENT_CONTRACT_ID", "").strip()
            plan_id = row.get("CURRENT_PLAN_ID", "").strip()
            plan_name = row.get("CURRENT_PLAN_NAME", "").strip()

            if not contract_id:
                continue

            # The crosswalk contains both previous and current year rows, so the same plan can appear more than once.
            dedup_key = (contract_id, plan_id, plan_name)
            if dedup_key in seen:
                continue
            seen.add(dedup_key)

            if contract_id not in crosswalk:
                crosswalk[contract_id] = []

            crosswalk[contract_id].append({"plan_id": plan_id, "plan_name": plan_name})

    return crosswalk


def group_payers_by_name(payers):
    """
    Re-group the per-contract payer dict into a dict keyed by normalized payer name.

    Returns
    -------
    dict[str, dict]
        Mapping of normalized_name ->
            {
                "canonical_name": str,          # first raw name seen (sorted by contract_id)
                "contracts": [                  # all contracts sharing this normalized name
                    {"contract_id": str, "url": str, "endpoint_key": str},
                    ...
                ]
            }
    """
    groups = {}
    for contract_id in sorted(payers.keys()):
        info = payers[contract_id]
        payer_name = info["payer_name"]
        url = info["url"]
        norm = normalize_legal_name(payer_legal_name=payer_name)

        if norm not in groups:
            groups[norm] = {
                "canonical_name": payer_name,
                "contracts": [],
            }
        groups[norm]["contracts"].append({
            "contract_id": contract_id,
            "url": url,
            "endpoint_key": info.get("endpoint_key", ENDPOINT_KEY),
        })

    return groups


def build_well_known_json(normalized_name, canonical_name, contract_entries, crosswalk,
                          existing_f_plan_ids=None):
    """
    Construct the well-known payer JSON document for one logical payer.

    The FPI is derived from the normalized payer name.  All contracts that share
    the same normalized name are included as additional identifiers.  Plans from
    different contracts that point to different FHIR endpoint URLs are placed in
    separate plan_groups so that endpoint routing remains unambiguous.

    Parameters
    ----------
    normalized_name : str
        The all-lowercase, special-character-free payer name key (used for FPI).
    canonical_name : str
        The human-readable payer name to store in payerLegalName.
    contract_entries : list[dict]
        Each entry has "contract_id" and "url".
    crosswalk : dict[str, list]
        Maps contract_id -> list of {plan_id, plan_name} dicts.
    existing_f_plan_ids : dict[str, str] | None
        Maps an already-published plan identifier value (e.g. "H3146-001") to the
        f_plan_id previously assigned to it, so that value is preserved instead
        of being randomly regenerated.

    Returns
    -------
    tuple[dict, str, int]
        (well-known JSON document, fpi string, total plan count)
    """
    # FPI_maker_cli normalizes the legal name internally for LEGAL_NAME_HASH,
    # so passing the raw canonical name here yields the same FPI as passing
    # the pre-normalized name.  That means the recorded "fpi_source_value"
    # below (the raw legal name) genuinely reproduces the FPI.
    fpi = generate_fpi(system_id=FPI_SYSTEM_ID, payer_id_value=canonical_name)
    existing_f_plan_ids = existing_f_plan_ids or {}

    # Build the identifier block.
    #
    # New multi-FPI format (WellKnownFileFormat.md, merged in PR #1):
    #   - Every identifier entry MUST include "is_fpi" (Boolean).
    #   - The FPI entry has is_fpi: true and carries payerLegalName inside it.
    #     payerLegalName is NO LONGER a top-level field.
    #   - Every non-FPI identifier has is_fpi: false and MUST carry parent_fpi
    #     (the UUID of the owning FPI in this same file).
    #   - Every plan identifier MUST carry parent_fpi and a random f_plan_id.
    identifier = [{
        "system": SYSTEM_FPI,
        "value": fpi,
        "is_fpi": True,
        "payerLegalName": canonical_name,
        "fpi_source_system": SYSTEM_LEGAL_NAME_HASH,
        "fpi_source_value": canonical_name,
    }]
    for entry in contract_entries:
        identifier.append({
            "system": SYSTEM_CMS_CONTRACT_ID,
            "value": entry["contract_id"],
            "is_fpi": False,
            "parent_fpi": fpi,
        })

    # Group plans by (endpoint key, endpoint URL) so that each distinct endpoint
    # becomes its own plan_group.  The key is part of the bucket identity because
    # the same payer could publish a FHIR directory for one contract and a CMS
    # machine-readable index for another; those must not be merged.  The
    # empty-URL bucket is the "endpoint unknown" case: those plans are still
    # published, in a plan_group that asserts no endpoint.
    endpoint_to_plans = {}   # (endpoint_key, url) -> list of {contract_plan_id, plan_name}
    for entry in contract_entries:
        contract_id = entry["contract_id"]
        url = entry["url"]
        # An empty URL asserts nothing, so it collapses into a single bucket
        # regardless of which key the row would otherwise have used.
        bucket = (entry.get("endpoint_key", ENDPOINT_KEY), url) if url else ("", "")
        plans = crosswalk.get(contract_id, [])
        if bucket not in endpoint_to_plans:
            endpoint_to_plans[bucket] = []
        # Deduplicate plans within the same endpoint bucket.
        seen_plan_keys = {(p["contract_plan_id"], p["plan_name"])
                          for p in endpoint_to_plans[bucket]}
        for plan in plans:
            # The full Medicare plan identifier is the contract number plus the
            # plan segment, joined by a hyphen (e.g. "H3146-001").
            contract_plan_id = f"{contract_id}-{plan['plan_id']}"
            key = (contract_plan_id, plan["plan_name"])
            if key not in seen_plan_keys:
                endpoint_to_plans[bucket].append({
                    "contract_plan_id": contract_plan_id,
                    "plan_name": plan["plan_name"],
                })
                seen_plan_keys.add(key)

    plan_groups = []
    total_plans = 0
    for (endpoint_key, url), plans in sorted(endpoint_to_plans.items()):
        plan_identifiers = []
        for plan in plans:
            entry = {
                "system": SYSTEM_MEDICARE_PLAN,
                "value": plan["contract_plan_id"],
                # parent_fpi links this plan to the owning FPI (validation rule 5 & 6).
                "parent_fpi": fpi,
                # f_plan_id is a UUIDv4 unique to this plan entry.  It is minted
                # once and then reused on later runs (see load_existing_f_plan_ids)
                # so that re-seeding does not churn every published plan entry.
                "f_plan_id": existing_f_plan_ids.get(
                    plan["contract_plan_id"], str(uuid.uuid4())
                ),
            }
            if plan["plan_name"]:
                entry["plan_name"] = plan["plan_name"]
            plan_identifiers.append(entry)
        # An empty url means no endpoint is known for these plans.  Per
        # WellKnownFileFormat.md, omitting an endpoint key means the index makes
        # no assertion for that protocol, so the key is left out entirely rather
        # than written as null or as an empty string.
        plan_endpoints = {endpoint_key: url} if url else {}
        plan_groups.append({
            "plan_identifiers": plan_identifiers,
            "plan_endpoints": plan_endpoints,
        })
        total_plans += len(plan_identifiers)

    # payerLegalName is now inside the FPI identifier entry, NOT at the top level.
    doc = {
        "copied_from_url": None,
        "resourceType": RESOURCE_TYPE,
        "identifier": identifier,
        "plan_groups": plan_groups,
        "is_seeded": True,
    }

    return doc, fpi, total_plans


# The complete set of top-level keys the seed writes.
# NOTE: "payerLegalName" is no longer a top-level key; it lives inside the FPI identifier entry.
SEED_TOP_LEVEL_KEYS = {"copied_from_url", "is_seeded", "resourceType", "identifier", "plan_groups"}

# Keys the seed writes inside each plan_identifier entry.
# parent_fpi and f_plan_id are new required fields from the multi-FPI format (PR #1).
SEED_PLAN_IDENTIFIER_KEYS = {"system", "value", "plan_name", "parent_fpi", "f_plan_id"}

# Keys the seed writes inside each plan_group entry.
SEED_PLAN_GROUP_KEYS = {"plan_identifiers", "plan_endpoints"}

# Keys the seed writes inside each identifier entry.
# is_fpi is required on every identifier entry (multi-FPI format).
# parent_fpi is required on non-FPI entries (is_fpi: false).
# payerLegalName, fpi_source_system, fpi_source_value appear only on the FPI entry (is_fpi: true).
SEED_IDENTIFIER_KEYS = {"system", "value", "is_fpi", "parent_fpi", "payerLegalName",
                        "fpi_source_system", "fpi_source_value"}

# Endpoint keys the seed ever writes (at most one per plan_group).
SEED_ENDPOINT_KEYS = {ENDPOINT_KEY, MACHINE_READABLE_ENDPOINT_KEY}


def collect_extra_fields(existing_doc, seed_doc):
    """Return a list of human-readable descriptions of any fields present in existing_doc
    that go beyond what the seed would produce (seed_doc is used only to identify the
    seed-generated endpoint key for that contract)."""
    extras = []

    # --- Top-level keys ---
    for key in existing_doc:
        if key not in SEED_TOP_LEVEL_KEYS:
            extras.append(f"top-level key '{key}'")

    # --- identifier entries ---
    for i, id_entry in enumerate(existing_doc.get("identifier", [])):
        for key in id_entry:
            if key not in SEED_IDENTIFIER_KEYS:
                extras.append(f"identifier[{i}] key '{key}'")

    # --- plan_groups ---
    for gi, group in enumerate(existing_doc.get("plan_groups", [])):
        for key in group:
            if key not in SEED_PLAN_GROUP_KEYS:
                extras.append(f"plan_groups[{gi}] key '{key}'")

        # plan_identifiers entries
        for pi, plan_id_entry in enumerate(group.get("plan_identifiers", [])):
            for key in plan_id_entry:
                if key not in SEED_PLAN_IDENTIFIER_KEYS:
                    extras.append(f"plan_groups[{gi}].plan_identifiers[{pi}] key '{key}'")

        # plan_endpoints keys
        for ep_key in group.get("plan_endpoints", {}):
            if ep_key not in SEED_ENDPOINT_KEYS:
                extras.append(f"plan_groups[{gi}].plan_endpoints key '{ep_key}'")

    return extras


def load_existing_f_plan_ids(*, output_dir: str) -> dict:
    """Return a mapping of plan identifier value -> f_plan_id already on disk for this payer.

    f_plan_id is a random UUIDv4 with no derivable source, so regenerating it on
    every run would rewrite every plan entry in every file and bury real changes
    in churn.  Downstream consumers may also have stored these values.  The seed
    therefore reuses any f_plan_id it has already published for a given plan and
    mints a new one only for plans it has not seen before.
    """
    existing = {}
    if not os.path.isdir(output_dir):
        return existing
    for existing_name in sorted(os.listdir(output_dir)):
        if not existing_name.endswith(".well_known_payer.json"):
            continue
        try:
            with open(os.path.join(output_dir, existing_name), encoding="utf-8") as existing_file:
                existing_doc = json.load(existing_file)
        except (json.JSONDecodeError, OSError):
            continue
        for group in existing_doc.get("plan_groups", []):
            for plan_entry in group.get("plan_identifiers", []):
                value = plan_entry.get("value")
                f_plan_id = plan_entry.get("f_plan_id")
                if value and f_plan_id:
                    existing.setdefault(value, f_plan_id)
    return existing


def directory_contains_curated_file(*, output_dir: str) -> bool:
    """Return True if *output_dir* holds any well-known file that is manually curated.

    A file is considered manually curated when its "is_seeded" flag is anything
    other than exactly true (false, absent, or unreadable JSON).  Because
    curated files may carry FPIs derived from different identifier systems
    (and therefore different filenames), the seed must check the whole payer
    directory — not just its own target filename — before writing anything.
    """
    if not os.path.isdir(output_dir):
        return False
    for existing_name in sorted(os.listdir(output_dir)):
        if not existing_name.endswith(".well_known_payer.json"):
            continue
        existing_path = os.path.join(output_dir, existing_name)
        try:
            with open(existing_path, encoding="utf-8") as existing_file:
                existing_doc = json.load(existing_file)
        except (json.JSONDecodeError, OSError):
            # Unreadable files are treated as curated so the seed stays hands-off.
            return True
        if existing_doc.get("is_seeded", False) is not True:
            return True
    return False


def write_output_file(doc, payer_name, fpi):
    """Write the well-known JSON document to the appropriate subdirectory under payer_index_files/medicare_advantage/.

    Overwrite policy:
      1. If the payer's directory contains ANY manually curated file (a file
         whose "is_seeded" flag is not exactly true), the seed skips the whole
         payer.  Curated files may use FPIs from different identifier systems,
         so their filenames will not match the seed's target filename — the
         directory-level check is what protects them.
      2. If the seed's own target file exists with is_seeded exactly true but
         contains fields beyond what the seed produces, it has been enriched
         and will NOT be overwritten.
    A warning is printed and the function returns (filepath, skipped=True) when skipping.
    """
    dir_name = safe_name(payer_name)
    output_dir = os.path.join(OUTPUT_BASE_DIR, dir_name)

    filename = f"{dir_name}_{fpi}.well_known_payer.json"
    filepath = os.path.join(output_dir, filename)

    # Guard 1: never touch a payer directory that holds manually curated files.
    if directory_contains_curated_file(output_dir=output_dir):
        print(f"    !! SKIPPED (directory contains manually curated file(s) — is_seeded not true):")
        return filepath, True

    os.makedirs(output_dir, exist_ok=True)

    if os.path.exists(filepath):
        try:
            with open(filepath, encoding="utf-8") as f:
                existing_doc = json.load(f)

            # Guard 2: check whether the file has grown beyond the seed's own fields.
            extra_fields = collect_extra_fields(existing_doc, doc)
            if extra_fields:
                print(f"    !! SKIPPED (file has grown beyond seed data):")
                for field in extra_fields:
                    print(f"       + {field}")
                return filepath, True
        except (json.JSONDecodeError, OSError) as exc:
            print(f"    !! WARNING: Could not read existing file for comparison ({exc}). Overwriting.")

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2)
        f.write("\n")

    return filepath, False


def main():
    print("=" * 60)
    print("Medicare Advantage Well-Known JSON Seed Generator")
    print("(Payer-Name-Based FPI Mode)")
    print("=" * 60)
    print()
    print("Identifier strategy: FPI is derived from the normalized payer name")
    print("  (lowercase, all non-alphanumeric characters removed).")
    print("  Multiple contract IDs sharing the same normalized name are merged")
    print("  into a single well-known JSON file under one FPI.")
    print()
    print("Coverage: every payer with plans in the crosswalk is seeded.  Payers")
    print("  with no usable endpoint URL get a file whose plan_group asserts no")
    print("  endpoint, so their FPI and plan roster are still published.")
    print()
    print("Endpoint keys written:")
    print(f"  FHIR JSON             -> {ENDPOINT_KEY}")
    print(f"  Machine-readable JSON -> {MACHINE_READABLE_ENDPOINT_KEY}")
    print()

    print(f"Loading payer URL list from:\n  {PAYER_URL_FILE}")
    payers, url_stats = load_payer_urls(PAYER_URL_FILE)

    print(f"\nLoading plan crosswalk from:\n  {PLAN_CROSSWALK_FILE}")
    crosswalk = load_plan_crosswalk(PLAN_CROSSWALK_FILE)

    # Group contracts by normalized payer name.
    name_groups = group_payers_by_name(payers)

    print(f"\nOutput directory:\n  {OUTPUT_BASE_DIR}")
    print(f"\nUnique contract IDs loaded:  {len(payers)}")
    print(f"Unique payer names (groups): {len(name_groups)}")
    print(f"  → {len(payers) - len(name_groups)} contract(s) consolidated by shared name")
    print()

    # Contracts that carry plans in the crosswalk but never appear in the payer
    # URL list have no legal name in any source file.  The FPI is a hash of the
    # legal name and contract IDs must never be used as an FPI source, so these
    # cannot be seeded.  They are reported so the gap stays visible.
    unnamed_contracts = sorted(set(crosswalk) - set(payers))
    unnamed_plan_count = sum(len(crosswalk[c]) for c in unnamed_contracts)

    files_written = 0
    files_skipped_enriched = 0
    payers_no_plans = 0
    files_without_endpoint = 0

    for normalized_name, group in sorted(name_groups.items()):
        canonical_name = group["canonical_name"]
        contract_entries = group["contracts"]

        # Check whether any contract in this group has crosswalk plans.
        total_plans_available = sum(
            len(crosswalk.get(e["contract_id"], [])) for e in contract_entries
        )
        if total_plans_available == 0:
            payers_no_plans += 1
            contract_ids = ", ".join(e["contract_id"] for e in contract_entries)
            print(f"  [{contract_ids}] {canonical_name}  -- SKIPPED (no crosswalk plans)")
            continue

        # Reuse f_plan_id values already published for this payer so that
        # re-running the seed does not churn every existing plan entry.
        payer_dir = os.path.join(OUTPUT_BASE_DIR, safe_name(canonical_name))
        existing_f_plan_ids = load_existing_f_plan_ids(output_dir=payer_dir)

        doc, fpi, plan_count = build_well_known_json(
            normalized_name, canonical_name, contract_entries, crosswalk,
            existing_f_plan_ids=existing_f_plan_ids,
        )
        filepath, skipped = write_output_file(doc, canonical_name, fpi)

        contract_ids = ", ".join(e["contract_id"] for e in contract_entries)
        print(f"  [{contract_ids}] {canonical_name}")
        print(f"    -> {os.path.relpath(filepath, REPO_ROOT)}")

        if skipped:
            files_skipped_enriched += 1
            print(f"       Plans: {plan_count}, FPI: {fpi}  [NOT overwritten — enriched beyond seed]")
        else:
            files_written += 1
            n_contracts = len(contract_entries)
            n_groups = len(doc["plan_groups"])
            has_endpoint = any(g["plan_endpoints"] for g in doc["plan_groups"])
            if not has_endpoint:
                files_without_endpoint += 1
            endpoint_note = "" if has_endpoint else "  [no endpoint known]"
            print(f"       Contracts: {n_contracts}, Plan groups: {n_groups}, "
                  f"Plans: {plan_count}, FPI: {fpi}{endpoint_note}")

    print()
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(f"  Total rows in payer URL list:          {url_stats['total']}")
    print(f"  Rows with no contract ID / name:       {url_stats['skipped_no_contract_id']}")
    print(f"  Processed contract IDs:                {url_stats['processed']}")
    print(f"    ...FHIR provider directory URL:      {url_stats['with_url']}")
    print(f"    ...CMS machine-readable index URL:   {url_stats['machine_readable']}")
    print(f"    ...with an empty URL cell:           {url_stats['no_url']}")
    print(f"    ...multiple URLs (no URL used):      {url_stats['multi_url']}")
    print(f"  Unique normalized payer names:         {len(name_groups)}")
    print(f"  Contracts merged by shared name:       {url_stats['processed'] - len(name_groups)}")
    print(f"  Payer names with no crosswalk plans:   {payers_no_plans}")
    print(f"  Well-known JSON files written:         {files_written}")
    print(f"    ...of those, asserting no endpoint:  {files_without_endpoint}")
    print(f"  Skipped (enriched beyond seed data):   {files_skipped_enriched}")
    print()
    print(f"  Crosswalk contracts with no legal name in the payer URL list:")
    print(f"    Contracts: {len(unnamed_contracts)}, Plans: {unnamed_plan_count}")
    print(f"    These cannot be seeded: the FPI is a hash of the payer legal")
    print(f"    name, and a contract ID must never be used as an FPI source.")
    if unnamed_contracts:
        preview = ", ".join(unnamed_contracts[:12])
        suffix = ", ..." if len(unnamed_contracts) > 12 else ""
        print(f"    e.g. {preview}{suffix}")
    print()


if __name__ == "__main__":
    main()
